# Generated by Django 5.2.7 on 2025-10-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='booking_status',
            new_name='is_booked',
        ),
    ]
